/*** Generated by streamline 0.2.5 - DO NOT EDIT ***/
var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb,__trap=__rt.__trap,__propagate=__rt.__propagate,__future=__rt.__future,__setEF=__rt.__setEF,__g=__rt.__g;
            (function main(_) {
              var __frame = {
                name: "main",
                line: 1
              };
              return __func(_, this, arguments, main, 0, __frame, function __$main() {
/*     1 */     console.log("hello ...");
/*     2 */     return setTimeout(__cb(_, __frame, 1, 0, function __$main() {
/*     3 */       console.log("... world");
                  _();
/*     2 */     }, true), 1000);
              });
            }).call(this, __trap);
